# Generated by Django 5.2.4 on 2025-07-26 13:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Write your blog content here. You can insert images and format text.'),
        ),
    ]
