# Generated by Django 5.2.4 on 2025-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Write your blog content here. You can insert text manually (no rich editor).'),
        ),
    ]
