# Generated by Django 5.2.4 on 2025-07-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Paragraph number after which to insert this media'),
        ),
    ]
