# Generated by Django 5.2.4 on 2025-07-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postmedia_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Post Media', 'verbose_name_plural': 'Post Media Items'},
        ),
        migrations.AddField(
            model_name='postmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption for the media item.', max_length=255, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(help_text='Upload your media file here.', upload_to='post_media/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='image', max_length=10, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Paragraph number (starting from 0) after which this media should appear.', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(help_text='Attach media to a specific blog post.', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blog.post', verbose_name='Post'),
        ),
    ]
