# Generated by Django 5.2.4 on 2025-07-27 12:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postmedia_options_postmedia_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(help_text='Write your blog content here with rich formatting (using TinyMCE editor).'),
        ),
        migrations.DeleteModel(
            name='PostMedia',
        ),
    ]
