# Generated by Django 5.2.4 on 2025-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_buy_link_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(help_text='Enter price (e.g. 23.99, Free, Contact for price)', max_length=100),
        ),
    ]
